# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: debug-statements
      - id: destroyed-symlinks
#      - id: detect-aws-credentials
      - id: detect-private-key
#      - id: double-quote-string-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
#      - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: name-tests-test
#      - id: no-commit-to-branch
      - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: Run black code formatter for Python
        args: # arguments to configure black
          - "--line-length=120"
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8 # https://github.com/DmytroLitvinov/awesome-flake8-extensions
        additional_dependencies:
          - flake8-bugbear
          - flake8-print
        args: # arguments to configure flake8
          # making isort line length compatible with black
          - "--max-line-length=120"
          - "--max-complexity=15"
          - "--statistics"
          - "--count"
          - "--select=B,C,E,F,W,T4,B9,W504"

          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          # ignored errors:
          #                E203 is not compatible with black
          #                W503 goes against pep8
          - "--ignore=E203, W503, E266, F405, F403"
          - "--per-file-ignores=errmem_server/*:C901"
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/crate-ci/typos
    rev: v1.13.6
    hooks:
      - id: typos
#  - repo: https://github.com/jazzband/pip-tools
#    rev: 6.12.0
#    hooks:
#      - id: pip-compile
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.10.1
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.210
    hooks:
      - id: ruff
        args: ["--line-length=120"]
